apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifacts-
spec:
  entrypoint: artiface-example
  templates:
    - name: artiface-example
      steps:
      - - name: generate-artifact
          template: whalesay
      - - name: consume-artiface
          template: print-message
          arguments:
            artifacts: 
            - name: message
              from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

    - name: whalesay
      container:
        image:  docker/whalesay
        command: [sh,-c]
        args: ["cowsay hello artifact | tee /tmp/hello_artifact.txt"]
      outputs:
        artifacts:
          - name: hello-art
            path: /tmp/hello_artifact.txt

    - name: print-message
      inputs:
        artifacts:
          - name: message
            path: tmp/message
      container:
        image: alpine:3.7
        command: [sh, -c]
        args: ["cat /tmp/message"]