apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: start
  templates:
  - name: start
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
          