apiVersion: argoproj.io/v1alpha
kind: Workflow
metadata:
  generateName: secret-

spec:
  entrypoint: whalesay
  volumes:
  - name: my-secret-vol
    secret:
      secretName: my-secret # name in k8s
  templates:
  - name: whalesay
    container:
      image: docker/whalesay
      command: [sh, -c]
      args: ['
        echo "secret from env: $MYSECRETPASSWORD";
        echo "secret from file: `cat /secret/mountpath/mypassword`"
      ']
      env:
      - name: MYPWD
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: mypassword
      volumeMounts:
      - name: my-secret-vol
        mountPath: "/secret/mountpath"
