apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: timeout-

spec:
  entrypoint: deadline
  templates:
  - name: deadline
    container:
      image: alpine:3.7
      command: [sh , -c]
      args: ["echo sleeping for 1m; sleep 60; echo done"]

    activeDeadlineSeconds: 30